global:
  # Scrape targets every five seconds (default: one minute)
  # This enables data to be gathered quickly for this demonstration
  scrape_interval: 3s

  # Also evaluate alerting rules every five seconds
  # (This will be useful later in this guide)
  evaluation_interval: 3s

scrape_configs:
  - job_name: "mysqld_exporter"
    static_configs:
      - targets: ["mysqld_exporter:9104"]
